services:

  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: Mirik
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - micro-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "user_db", "-U", "Mirik"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-company:
    image: postgres:16
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: Mirik
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - micro-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "company_db", "-U", "Mirik"]
      interval: 5s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - micro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - micro-network
    depends_on:
      config-server:
        condition: service_started # Важно: используем started, чтобы избежать deadlock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 15

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME: Mirik
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Указываем сервисам, где искать инфраструктуру внутри Docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      postgres-user:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

  company-service:
    build:
      context: .
      dockerfile: company-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-company:5432/company_db
      SPRING_DATASOURCE_USERNAME: Mirik
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      postgres-company:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_started

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - micro-network
    depends_on:
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_started
      company-service:
        condition: service_started

networks:
  micro-network:
    driver: bridge